### PR TITLE
Trivial tweaks to allow usage on PyVersion >= 2.7 + typo fixes

### PR DESCRIPTION
**Pull request by odeke-em**
- Fixed some typos.
- Allowing for running of tool on
  python version >= 2.7 to 3.5.
  Could add portability way back to 2.4 but
  that'll require usage of optparse vs argparse +
  a little more work but this is open for discussion.

### CODE REVIEW

**Comment by macpd** [comment]
Apologies for the delay.  Before I can merge your pull request you must sign the
[Google Individual Contributor License Agreement](https://developers.google.com/open-source/cla/individual?csw=1) (CLA).

google's official blurb (which I'll add to the repo soon so as to prevent this friction in the future):
"""
Want to contribute? Great! First, read this page (including the small print at the end).

### Before you contribute
Before we can use your code, you must sign the
[Google Individual Contributor License Agreement](https://developers.google.com/open-source/cla/individual?csw=1)
(CLA), which you can do online. The CLA is necessary mainly because you own the
copyright to your changes, even after your contribution becomes part of our
codebase, so we need your permission to use and distribute your code. We also
need to be sure of various other things—for instance that you'll tell us if you
know that your code infringes on other people's patents. You don't have to sign
the CLA until after you've submitted your code for review and a member has
approved it, but you must do it before we can put your code into our codebase.
Before you start working on a larger contribution, you should get in touch with
us first through the issue tracker with your idea so that we can help out and
possibly guide you. Coordinating up front makes it much easier to avoid
frustration later on.

### Code reviews
All submissions, including submissions by project members, require review. We
use Github pull requests for this purpose.

### The small print
Contributions made by corporations are covered by a different agreement than
the one above, the Software Grant and Corporate Contributor License Agreement.
"""

**Comment by macpd** [comment]
my URL decoding does not work as implemented with python v3 because of how the hex is decoded as a string. I'll fix this in another branch.

**Comment by odeke-em** [comment]
@macpd thanks for the information. CLA was already signed. I'll take a look at this issue later this evening when am back home from work.

**Comment by macpd** [comment]
great, and thanks for contributing!

**Comment by macpd** [comment]
ok, i've merged the trivial fix into master. please pull these changes into your branch and let me know once you've done so.

**Comment by macpd** [comment]
oops, not enough git lately. please ignore my last comment.

**Comment by odeke-em** [comment]
@macpd Got back home and just saw that you fixed it. Thanks for the review, merge and fixes!

**Pull request merged**
